### PR TITLE
feat : add wishlist page

### PR DESCRIPTION
**Pull request by Kevin-Solomon**
# Wishlist Page

image

[Wishlist Page CodeSandbox Link](https://6o9ol.csb.app/pages/wishlist/wishlist.html)

### CODE REVIEW

**Review by mohammed-sas — APPROVED** [review]
pr good to merge

**Review by irfan-nawaz — APPROVED** [review]
looking good

**Review by VishalPatil18 — APPROVED** [review]
You can have some empty space after the cards at the bottom. Apart from that rest looks good. 👍

**Comment by Kevin-Solomon** [comment]
> You can have some empty space after the cards at the bottom. Apart from that rest looks good. 👍

I will make a completely different eCommerce Card.
Thanks for the suggestion, Vishal.

**Review by sagar455 — APPROVED** [review]
Looks good👍

**Review by irfan-nawaz — APPROVED** [review]
👍🏼

**Pull request merged**
